### ISSUE TITLE
Erro ao importar a biblioteca no node 

### ISSUE THREAD

**Issue by JoaoSeger** [bayesjs/bayesjs#26]
Ao tentar importar a lib está retornando esse erro:

ReferenceError: window is not defined

**Comment by nolleto** [comment]
Olá @JoaoSeger , atualmente ando meio sem tempo 😓 mas vou tentar dar uma olhada nisso essa semana 😄

**Comment by nolleto** [comment]
Boa tarde @JoaoSeger , subi a `v0.4.1` que corrige esse erro. Qualquer outro problema ou melhoria, só criar uma _issue_.

**Comment by JoaoSeger** [comment]
Obrigado pela atenção e desculpe pelo incomodo.
