### ISSUE TITLE
Export Types

### ISSUE THREAD

**Issue by Flowan24** [bayesjs/bayesjs#30]
It seems that the npm bayesjs-package does not contain the internal type definitions like INetwork etc.. nor export them correctly. 

I forked this project a while ago and changed the build process to use tsc instead of webpack and added to main the index.ts file a line to export all types. (https://github.com/Flowan24/bayesjs/blob/master/src/index.ts). 

It might be interesting if future releases export all internally used types.

**Comment by nolleto** [comment]
That awesome. If you want to you can open a PR with these changes otherwise, I will open a PR in the future 😄

**Comment by Flowan24** [comment]
I checked out your project, created a local branch and committed all changes. Now I am not allowed to push my branch to open a new PR from it. How should I continue, could you add me as a participant?

**Comment by nolleto** [comment]
I recommend you to fork this repo and make the changes at the forked repo. I do that to every repo that I contribute 😄 

Here are the steps:

1. Fork the repo (just once)
2. Clone the forked repo in your machine
3. Create a new branch (not necessary but recommended)
4. Make your changes
5. Push all your changes
6. Create a Pull Request from your forked repo to the original repo

Remember to:
- Always read `CONTRIBUTING.md` first (if exists)
- Create commits with a good description
- Create Pull Request with a good description

Here is one repo that may help you to do all this process: https://github.com/firstcontributions/first-contributions

😃

**Comment by Flowan24** [comment]
Hi!
Thank you for your introduction :). 

I followed your instructions and links and created a pull request as you suggested. Please review my changes: https://github.com/bayesjs/bayesjs/pull/38, if something comes up just drop a message...

**Comment by nolleto** [comment]
Done in [v0.5.0](https://www.npmjs.com/package/bayesjs/v/0.5.0) 🎉

**Comment by Flowan24** [comment]
:)
