### ISSUE TITLE
junction tree algorithm gives wrong inferences

### ISSUE THREAD

**Issue by dlewissandy** [bayesjs/bayesjs#64]
For certain network topologies, the junction tree algorithm returns equal probability of all outcomes for certain nodes.      enumeration and variable elimination for the same networks return the correct inferences for all outcomes.   

For example, the attached network aways reports a 50% probability of all outcomes for the random variable "B"

```
console.log(BAYES.inferences.junctiontree.infer(examplenet,{ B: "Yes"}, {} ))
```
returns the incorrect value:
```
0.5
```

However,
```
console.log(BAYES.inferences.variableElimination.infer(examplenet,{ B: "Yes"}, {} ))
```
results in:
```
0.7500000000000001
```
Which is correct within machine epsilon

## Example network
```json
const examplenet = {
  "B": {
    "id": "B",
    "states": [
      "Yes",
      "No"
    ],
    "parents": [
      "A"
    ],
    "cpt": [
      {
        "when": {
          "A": "Yes"
        },
        "then": {
          "Yes": 0.9,
          "No": 0.1
        }
      },
      {
        "when": {
          "A": "No"
        },
        "then": {
          "Yes": 0.4,
          "No": 0.6
        }
      }
    ]
  },
  "C": {
    "id": "C",
    "states": [
      "Yes",
      "No"
    ],
    "parents": [
      "A"
    ],
    "cpt": [
      {
        "when": {
          "A": "Yes"
        },
        "then": {
          "Yes": 0.01,
          "No": 0.99
        }
      },
      {
        "when": {
          "A": "No"
        },
        "then": {
          "Yes": 0.1,
          "No": 0.9
        }
      }
    ]
  },
  "E": {
    "id": "E",
    "states": [
      "Yes",
      "No"
    ],
    "parents": [
      "B",
      "D"
    ],
    "cpt": [
      {
        "when": {
          "B": "Yes",
          "D": "Yes"
        },
        "then": {
          "Yes": 0.02,
          "No": 0.98
        }
      },
      {
        "when": {
          "B": "No",
          "D": "Yes"
        },
        "then": {
          "Yes": 0.8,
          "No": 0.2
        }
      },
      {
        "when": {
          "B": "Yes",
          "D": "No"
        },
        "then": {
          "Yes": 0.01,
          "No": 0.99
        }
      },
      {
        "when": {
          "B": "No",
          "D": "No"
        },
        "then": {
          "Yes": 0.9,
          "No": 0.1
        }
      }
    ]
  },
  "D": {
    "id": "D",
    "states": [
      "Yes",
      "No"
    ],
    "parents": [
      "C"
    ],
    "cpt": [
      {
        "when": {
          "C": "Yes"
        },
        "then": {
          "Yes": 0.9,
          "No": 0.1
        }
      },
      {
        "when": {
          "C": "No"
        },
        "then": {
          "Yes": 0.3,
          "No": 0.7
        }
      }
    ]
  },
  "A": {
    "id": "A",
    "states": [
      "Yes",
      "No"
    ],
    "parents": [],
    "cpt": {
      "Yes": 0.7,
      "No": 0.3
    }
  }
}
```

**Comment by dlewissandy** [comment]
The clustering is performed properly, resulting in nodes: 
```
[{"id":"0","nodeIds":["D","C","A"]},{"id":"1","nodeIds":["D","B","E"]},{"id":"2","nodeIds":["D","B","A"]}]
```

however the separation sets appear to be incorrect:
```
[{"ca":"0","cb":"1","sharedNodes":["D"]},{"ca":"0","cb":"2","sharedNodes":["D","A"]}]
```
This tree does not have the running intersection property which is required for consistency.   Specifically, every separation set on the path between node 0 and node 2 should include every node in the intersection {"D","B"}.   

The correct separation sets for a junction tree should be should be:
[{"ca":"1","cb":"2","sharedNodes":["D","B"]},{"ca":"0","cb":"2","sharedNodes":["D","A"]}]

**Comment by dlewissandy** [comment]
It looks like replacing the function "remove circular separation sets" can be replaced with Kruskal's or Prim's algorithm.    I will create a branch with a fix.

**Comment by dlewissandy** [comment]
The problem appears to stem from the implementation of Prim's algorithm, which should return a maximum spanning tree for the complete cluster graph.   It looks like the sort order that is being used returns the minimal spanning tree.  I have created a branch to fix this, however it breaks many of the unit tests.   It is going to take a couple days to make sure that the test failures are actually to previously incorrect inferences.

**Comment by dlewissandy** [comment]
I have created a branch to fix the sorting order.   In doing so, I have uncovered an additional issue.   It looks like the cliques that are generated for the huge network are incorrect.   it is finding a clique containing nodes 2, 37 and 38.   Both the moralized and triangularized graphs look like they have the correct connections.    I will investigate this today.

**Comment by nolleto** [comment]
Hi @dlewissandy, sorry for the delay 😅 

Thanks for this investigation and the branch with the fix 🚀 

Can you create a PR with this branch? So, the CI will run the tests, lint, build.... and I can review your code. If everything is correct I can approve your PR and you or I can merge it.

As soon it gets merged, your code will go to `master` and a new version will be created in npm.

If it's your first time creating a PR you may find useful this repo: [First Contributions](https://github.com/firstcontributions/first-contributions)

**Comment by dlewissandy** [comment]
I have created a branch (locally) to fix this issue, and cannot push it upstream.

**Comment by nolleto** [comment]
You can not push it upstream. 

#### In your forked repo

You must push it then, go to the pull request page and click on `New pull request`.

You will see something like:

![image](https://user-images.githubusercontent.com/2437673/133482084-38a0d54f-9e62-4ad4-8418-6b16c50b95c5.png)

Then select your branch (in this example is `my-branch`)

![image](https://user-images.githubusercontent.com/2437673/133481808-4b20bd19-8cb6-4b59-ba4e-d4b4440796d6.png)

And create the pull request
![image](https://user-images.githubusercontent.com/2437673/133481849-22841dae-a167-4a43-8267-e43066373d95.png)


This will create a PR!

You can also click on `Compare & pull request` if your GitHub detects your branch.
![image](https://user-images.githubusercontent.com/2437673/133482360-5bf0f300-ff1e-4833-8f25-50cc543c613d.png)

This will also create a PR!

**Comment by nolleto** [comment]
I just check here the forked repos and your name is not on the list:

![image](https://user-images.githubusercontent.com/2437673/133490310-076b8f43-9985-48d6-b1b5-c2b223f1e845.png)
[link](https://github.com/bayesjs/bayesjs/network/members)

Try to fork first this repo.

If you need any help this repo has good instructions 😃 (you can also ask me)
https://github.com/firstcontributions/first-contributions#first-contributions

**Comment by nolleto** [comment]
I will review your PR ASAP. I'm just checking with the CI (Travis CI and Coveralls) is not running properly.

**Comment by nolleto** [comment]
Published https://github.com/bayesjs/bayesjs/releases/tag/v0.6.4
